version: "3.8"

services:
  ############################
  # EVOLUTION API
  ############################
  evolution-api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:v2.3.2
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres-evolution
      - redis-evolution
    ports:
      - "8080:8080"
    networks:
      - evolution_n8n_net
    volumes:
      - evolution_instances:/evolution/instances

  ############################
  # POSTGRES - EVOLUTION
  ############################
  postgres-evolution:
    container_name: postgres_evolution
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: evolution_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5436:5432" # acesso externo (opcional)
    volumes:
      - postgres_evolution_data:/var/lib/postgresql/data
    networks:
      - evolution_n8n_net

  ############################
  # REDIS - EVOLUTION
  ############################
  redis-evolution:
    container_name: redis_evolution
    image: redis:latest
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_evolution_data:/data
    networks:
      - evolution_n8n_net

  ############################
  # N8N
  ############################
  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n
    restart: always
    env_file:
      - .env
    ports:
      - "5678:5678"
    depends_on:
      - postgres-n8n
      - redis-n8n
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - evolution_n8n_net

  ############################
  # POSTGRES - N8N
  ############################
  postgres-n8n:
    container_name: postgres_n8n
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: n8n
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8npass
    volumes:
      - postgres_n8n_data:/var/lib/postgresql/data
    networks:
      - evolution_n8n_net

  ############################
  # REDIS - N8N
  ############################
  redis-n8n:
    container_name: redis_n8n
    image: redis:latest
    restart: always
    volumes:
      - redis_n8n_data:/data
    networks:
      - evolution_n8n_net

################################
# VOLUMES
################################
volumes:
  evolution_instances:
  postgres_evolution_data:
  redis_evolution_data:
  n8n_data:
  postgres_n8n_data:
  redis_n8n_data:

################################
# NETWORK
################################
networks:
  evolution_n8n_net:
    driver: bridge
